# Generated by Django 6.1.1 on 2026-09-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date d’ajout')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
